version: '3'
services:
  gubernator-1:
    image: ghcr.io/gubernator-io/gubernator:latest
    entrypoint: "/gubernator"
    environment:
      - GUBER_GRPC_ADDRESS=0.0.0.0:81
      - GUBER_HTTP_ADDRESS=0.0.0.0:80
      - GUBER_ADVERTISE_ADDRESS=gubernator-1:81
      - GUBER_MEMBERLIST_KNOWN_NODES=gubernator-1
    ports:
      - "9081:81"
      - "9080:80"

